SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio AS 'precio EUR', ROUND(precio*0.98,2) AS 'precio USD' FROM producto;
SELECT nombre as "Nombre de producto", precio as "Euros", precio * 1.2 as "Dólares" FROM producto;
SELECT UPPER(nombre) as "NOMBRE", precio as "PRECIO" FROM producto;
SELECT LOWER(nombre) as "nombre", precio as "precio" FROM producto;
SELECT nombre as "Nombre", UPPER(LEFT(nombre,2)) as "Iniciales" FROM fabricante;
SELECT nombre as "Nombre", ROUND(precio, 2) as "Precio" FROM producto;
SELECT nombre as "Nombre", TRUNCATE(precio, 0) as "Precio" FROM producto;
SELECT DISTINCT codigo_fabricante as "Código de Fabricante" FROM producto;
SELECT DISTINCT codigo_fabricante as "Código de Fabricante" FROM producto GROUP BY codigo_fabricante;
SELECT nombre as "Nombre" FROM fabricante ORDER BY nombre ASC;
SELECT nombre as "Nombre" FROM fabricante ORDER BY nombre DESC;
SELECT nombre as "Nombre" FROM fabricante ORDER BY nombre, nombre DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 3, 2;
SELECT nombre_producto, precio_en_euros FROM producto GROUP BY fabricante ORDER BY precio_en_euros LIMIT 1;
SELECT producto.nombre, MAX(producto.precio) as precio FROM producto GROUP BY producto.codigo ORDER BY precio DESC LIMIT 1;
SELECT producto.nombre FROM producto WHERE producto.codigo_fabricante = 2;
SELECT producto.nombre, producto.precio, fabricante.nombre as nombre_fabricante FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo ORDER BY nombre_fabricante;
SELECT producto.codigo, producto.nombre, producto.codigo_fabricante, fabricante.nombre as nombre_fabricante FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo;
SELECT p.codigo AS 'codigo producto', p.nombre AS producte, f.codigo AS 'codigo fabricante', f.nombre AS fabricant FROM producto p JOIN fabricante f ON (f.codigo = p.codigo_fabricante);
SELECT producto.nombre, MIN(producto.precio) as precio, fabricante.nombre as nombre_fabricante FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo GROUP BY producto.codigo ORDER BY precio LIMIT 1;
SELECT producto.nombre, MAX(producto.precio) as precio, fabricante.nombre as nombre_fabricante FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo GROUP BY producto.codigo ORDER BY precio DESC LIMIT 1;
SELECT producto.nombre, producto.precio, producto.codigo_fabricante, fabricante.nombre as nombre_fabricante FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Lenovo';
SELECT producto.nombre, producto.precio, producto.codigo_fabricante, fabricante.nombre as nombre_fabricante FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Crucial' AND producto.precio > 200;
SELECT producto.nombre, producto.precio, producto.codigo_fabricante, fabricante.nombre as nombre_fabricante FROM producto JOIN fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'Asus' OR fabricante.nombre = 'Hewlett-Packard' OR fabricante.nombre = 'Seagate';
SELECT f.nombre AS 'Fabricante', p.nombre AS 'Producto'FROM producto p JOIN fabricante f ON (f.codigo = p.codigo_fabricante) WHERE f.nombre IN ('Asus', 'Hewlett-Packard', 'Seagate');
SELECT p.nombre, p.precio FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre LIKE '%e';
SELECT f.nombre AS 'Fabricante', p.nombre AS 'Producto', precio FROM producto p JOIN fabricante f ON (f.codigo = p.codigo_fabricante) WHERE f.nombre LIKE '%w%';
SELECT p.nombre AS 'Producto', precio, f.nombre AS 'Fabricante'FROM producto p JOIN fabricante f ON (f.codigo = p.codigo_fabricante) WHERE precio >= 180 ORDER BY precio DESC, Producto ASC;
SELECT f.codigo, f.nombre FROM fabricante f JOIN producto p ON (f.codigo = p.codigo_fabricante) GROUP BY (f.codigo);
SELECT nombre FROM fabricante WHERE codigo NOT IN (SELECT codigo_fabricante FROM producto);
SELECT p.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Lenovo' ORDER BY p.precio DESC LIMIT 1;
SELECT p.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre = 'Hewlett-Packard' ORDER BY p.precio LIMIT 1;
SELECT p.codigo, p.nombre, p.precio, codigo_fabricante FROM producto p, fabricante f WHERE f.codigo = p.codigo_fabricante AND precio >= (SELECT p.precio FROM producto p, fabricante f WHERE f.codigo = p.codigo_fabricante AND f.nombre = 'Lenovo'ORDER BY p.precio DESC LIMIT 1 );
SELECT p.codigo, p.nombre, p.precio, codigo_fabricante FROM producto p, fabricante f WHERE f.codigo = p.codigo_fabricante AND f.nombre = 'Asus' AND precio >= (SELECT AVG(p.precio) FROM producto p, fabricante f WHERE f.codigo = p.codigo_fabricante AND f.nombre = 'Asus'ORDER BY p.precio DESC );
